// "use client"
import Link from "next/link"
import './globals.css'
import { Control } from "./Control";
// import {useEffect, useState} from "react";

export const metadata = {
    title: 'Web Tutorials',
    description: 'Generated by HSKim'
}

// Client-side Rendering 

// export default function RootLayout({ children }) {
// const [topics, setTopics] = useState([]);   useEffect(()=>{
// fetch('http://localhost:9999/topics')       .then((resp)=>{return
// resp.json();})       .then(result=> {         setTopics(result);       }); },
// []); 

// Server-side Rendering
export default async function RootLayout({ children }) {
    const resp = await fetch('http://localhost:9999/topics', { cache: 'no-cache' });
    const topics = await resp.json();
    return (
        <html>
            <body>
                <h1>
                    <Link href="/">WEB</Link>
                </h1>
                <ol>
                    {
                        topics.map((topic) => {
                            return (
                                <li key={topic.id}>
                                    <Link href={`/read/${topic.id}`}>{topic.title}</Link>
                                </li>
                            )
                        })
                    }
                </ol>
                {children}
                <Control />
            </body>
        </html>
    )
}
